### ISSUE TITLE
TODO: Merge files into one library.

### ISSUE THREAD

**Issue by 9000-volts** [podiumnet/engn.js#1]
The separate engn.js libraries must be merged into one to make it less frustrating for those wanting to use multiple of the tools. It is more convenient.

**Comment by mk5med** [comment]
yea, have it all in one you don't want to have people to download a bunch
of seperate libs each time

**Comment by 9000-volts** [comment]
@viktorKorolyuk the point was that each file was a separate library for its own purposes but then I decided most people will want to use most of the libraries
